### ISSUE TITLE
Update rubygems version

### ISSUE THREAD

**Issue by frenkel** [spohlenz/tinymce-rails-langs#10]
It seems current master is newer than the latest release. Would you be able to publish a new version? Thanks!

**Comment by frenkel** [comment]
Weird, according to your commits it is not.. It seems fr.js in git is named fr_FR.js in the gem. How can that be?

**Comment by spohlenz** [comment]
You are right. This is well overdue for another update and release. Working on that now.

The master branch was previously tracking the language packs for TinyMCE 3.x, with TinyMCE 4.x language packs in the tinymce-4 branch. This has now been switched so master tracks TinyMCE 4.x language packs and TinyMCE 3.x language packs are in the tinymce-3 branch.

**Comment by spohlenz** [comment]
Pushed tinymce-rails-langs 4.20160310 to rubygems.org.

**Comment by frenkel** [comment]
Great, thank you!
