### ISSUE TITLE
New version of tinymce-rails-langs for tinymce-rails 7.x

### ISSUE THREAD

**Issue by graaff** [spohlenz/tinymce-rails-langs#16]
I've noticed that the current gem release of tinymce-rails-langs requires tinymce-rails ~> 6.0. For us that means we can't update to tinymce-rails 7.0 yet because we also need some of the translations in tinymce-rails-langs.

Is a tinymce-rails 7.0 version planned? Is there something I could help with to make that happen?

**Comment by spohlenz** [comment]
Thanks for the reminder. I've just update the language files for TinyMCE 7.x and released a new version of the gem compatible with tinymce-rails 7.0.

**Comment by graaff** [comment]
Great! Thanks for the quick action (and for keeping up with the tinymce releases in general).
